apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  labels:
    app: node-web-app
spec:
  type: LoadBalancer
  selector:
    app: node-web-app
  ports:
    - name: http # Named port (recommended)
      protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Matches containerPort
  sessionAffinity: ClientIP # Optional: Sticky sessions
  ipFamilyPolicy: PreferDualStack # IPv4/IPv6 support
